version: '3.8'

services:
  practical_microservices_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: practical_microservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '0.0.0.0:5432:5432'
  message-db:
    image: ethangarofolo/message-db:latest
    ports:
      - '0.0.0.0:5433:5432'